name: $(ReleaseVersionNumber) Build $(Build)
variables:
  ReleaseVersionNumber: 1.0.4
  Build: $[counter(variables['ReleaseVersionNumber'], 1)]
  PrereleaseVersionNumber: $(ReleaseVersionNumber)-dev$(Build)
  AssemblyVersion: $(ReleaseVersionNumber).$(Build)
  InformationalVersion: $(ReleaseVersionNumber) build $(Build)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - src
pr:
  branches:
    include:
      - master
  paths:
    include:
      - src
      - test
jobs:
  - job:
    pool:
      vmImage: windows-latest
    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          feedsToUse: select
          vstsFeed: "xpike-daily"
          includeNuGetOrg: true
          projects: |
            **/*.csproj

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          arguments: --no-restore -c release -p:Version=$(AssemblyVersion) -p:"InformationalVersion=$(InformationalVersion)"
          projects: |
            src/**/*.csproj

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          publishTestResults: false
          arguments: --no-restore -c debug --logger trx -r $(Agent.TempDirectory)/TestResults -p:CollectCoverage=true -p:CoverletOutput="$(Agent.TempDirectory)/TestResults/" -p:CoverletOutputFormat="json%2cCobertura" -p:MergeWith="$(Agent.TempDirectory)/TestResults/coverage.json" 
          projects: |
            test/**/*.csproj

      - task: PublishCodeCoverageResults@1
        displayName: Publish code coverage results
        inputs:
          codeCoverageTool: "Cobertura"
          summaryFileLocation: "$(Agent.TempDirectory)/TestResults/coverage.cobertura.xml"

      - task: PublishTestResults@2
        displayName: Publish test results
        inputs:
          searchFolder: $(Agent.TempDirectory)/TestResults
          failTaskOnFailedTests: true
          mergeTestResults: true
          testResultsFormat: "VSTest"
          testResultsFiles: "**/*.trx"

      - task: DotNetCoreCLI@2
        displayName: Package unstable
        inputs:
          command: custom
          custom: pack
          arguments: -c release --no-build -p:PackageVersion=$(PrereleaseVersionNumber) -o $(Build.ArtifactStagingDirectory)/unstable
          projects: |
            src/**/*.csproj

      - task: DotNetCoreCLI@2
        displayName: Package stable for Nuget
        inputs:
          command: custom
          custom: pack
          arguments: -c release --no-build -p:PackageVersion=$(ReleaseVersionNumber) -o $(Build.ArtifactStagingDirectory)/stable
          projects: |
            src/**/*.csproj

      - task: PublishBuildArtifacts@1
        displayName: Publish Build Artifact

    
      